"""
TenderMind — Tenderlar ma'lumoti (Node.js dan Python ga o'tkazildi)
"""

TENDERS_DB = [
    # ── IT ──────────────────────────────────────────────────────────────
    {"id": "it-001", "soha": "it", "hudud": "toshkent", "status": "active", "isNew": True,
     "title": "Toshkent shahar davlat idoralarini IT infratuzilmasini modernizatsiyalash",
     "budget": "4 200 000 000", "budgetRaw": 4200000000, "probability": 87, "competitors": 3,
     "deadline": "2026-05-28", "postedDate": "2026-03-15",
     "tags": ["Tarmoq", "Server", "Bulut"], "org": "Toshkent shahar hokimiyati",
     "description": "Toshkent shahar 47 ta davlat idorasi uchun zamonaviy IT infratuzilma: fiber optik tarmoq, bulut serverlar, kiberxavfsizlik tizimi.",
     "requirements": ["ISO 27001 sertifikati", "5+ yillik tajriba", "200+ xodim"],
     "contactEmail": "it@tashkent.gov.uz", "contactPhone": "+998 71 239 01 01"},

    {"id": "it-002", "soha": "it", "hudud": "samarqand", "status": "active", "isNew": False,
     "title": "Samarqand viloyati elektron hukumat platformasini joriy etish",
     "budget": "2 800 000 000", "budgetRaw": 2800000000, "probability": 72, "competitors": 5,
     "deadline": "2026-05-10", "postedDate": "2026-03-10",
     "tags": ["E-gov", "Portal", "API"], "org": "Samarqand viloyat hokimiyati",
     "description": "Fuqarolar uchun 120+ ta davlat xizmati online platformasi. Mobile app + web portal.",
     "requirements": ["E-gov tajribasi", "REST API", "Mobile dev"],
     "contactEmail": "egov@samarkand.gov.uz", "contactPhone": "+998 66 234 00 00"},

    {"id": "it-003", "soha": "it", "hudud": "namangan", "status": "active", "isNew": False,
     "title": "Namangan shahar kuzatuv kamera tizimini o'rnatish",
     "budget": "1 500 000 000", "budgetRaw": 1500000000, "probability": 63, "competitors": 7,
     "deadline": "2026-05-20", "postedDate": "2026-03-05",
     "tags": ["Kamera", "Xavfsizlik", "AI"], "org": "Namangan shahar IIB",
     "description": "500+ ta HD kuzatuv kamera, AI yuz tanish tizimi, 24/7 monitoring markazi.",
     "requirements": ["Xavfsizlik litsenziyasi", "AI/ML tajriba"],
     "contactEmail": "info@namangan-iib.uz", "contactPhone": "+998 69 222 00 00"},

    {"id": "it-004", "soha": "it", "hudud": "andijon", "status": "active", "isNew": True,
     "title": "Andijon viloyati tibbiyot axborot tizimini modernizatsiyalash (MIS)",
     "budget": "1 800 000 000", "budgetRaw": 1800000000, "probability": 79, "competitors": 4,
     "deadline": "2026-06-10", "postedDate": "2026-03-20",
     "tags": ["MIS", "EMR", "HL7"], "org": "Andijon Tibbiyot Boshqarmasi",
     "description": "40+ poliklinika va kasalxona uchun yagona tibbiy axborot tizimi: elektron tibbiy karta, laboratoriya, aptek moduli.",
     "requirements": ["Tibbiy dasturiy ta'minot tajribasi", "HL7 FHIR", "Postgres"],
     "contactEmail": "mis@andijan-health.uz", "contactPhone": "+998 74 223 00 00"},

    {"id": "it-005", "soha": "it", "hudud": "fargona", "status": "active", "isNew": False,
     "title": "Farg'ona viloyati soliq inspeksiyasi uchun CRM tizimi",
     "budget": "950 000 000", "budgetRaw": 950000000, "probability": 68, "competitors": 6,
     "deadline": "2026-06-01", "postedDate": "2026-03-18",
     "tags": ["CRM", "Soliq", "Dashboard"], "org": "Farg'ona Soliq Boshqarmasi",
     "description": "Soliq to'lovchilar bilan ishlash uchun CRM, avtomatik hisobot, analytics dashboard.",
     "requirements": ["CRM tajribasi", "React yoki Vue.js", "PostgreSQL"],
     "contactEmail": "crm@fergana-tax.uz", "contactPhone": "+998 73 241 00 00"},

    {"id": "it-006", "soha": "it", "hudud": "toshkent", "status": "urgent", "isNew": True,
     "title": "Toshkent metro kartasi va to'lov tizimini yangilash",
     "budget": "3 600 000 000", "budgetRaw": 3600000000, "probability": 55, "competitors": 9,
     "deadline": "2026-04-20", "postedDate": "2026-03-25",
     "tags": ["NFC", "Contactless", "Payment"], "org": "Toshkent Metro",
     "description": "Barcha stantsiyalarga NFC kontaktsiz to'lov va QR kod tizimi o'rnatish. 30+ stantsiya.",
     "requirements": ["PCI DSS sertifikati", "NFC tajriba", "Banking protocol"],
     "contactEmail": "tender@tashkent-metro.uz", "contactPhone": "+998 71 244 00 00"},

    # ── QURILISH ─────────────────────────────────────────────────────────
    {"id": "q-001", "soha": "qurilish", "hudud": "toshkent", "status": "active", "isNew": False,
     "title": "Toshkent metro liniyasi — yangi bekatlar qurilishi",
     "budget": "12 800 000 000", "budgetRaw": 12800000000, "probability": 45, "competitors": 12,
     "deadline": "2026-04-15", "postedDate": "2026-02-01",
     "tags": ["Yer osti", "Beton", "Infra"], "org": "O'zbekiston Temir Yo'llari",
     "description": "M3 liniyasi: 6 ta yangi bekat, 8.5 km tunnel. Loyiha muddati 36 oy.",
     "requirements": ["TBM tajribasi", "ISO 9001", "500+ xodim", "5 mlrd kafolat"],
     "contactEmail": "tender@uzmetro.uz", "contactPhone": "+998 71 299 00 00"},

    {"id": "q-002", "soha": "qurilish", "hudud": "andijon", "status": "active", "isNew": False,
     "title": "Andijon viloyati yo'l ta'miri va qoplama yotqizish",
     "budget": "7 500 000 000", "budgetRaw": 7500000000, "probability": 68, "competitors": 4,
     "deadline": "2026-05-05", "postedDate": "2026-02-15",
     "tags": ["Asfalt", "Yo'l", "Region"], "org": "Andijon Avtomobil Yo'llari",
     "description": "120 km shaharlararo yo'l ta'miri va yangi asfalt qoplama.",
     "requirements": ["Yo'l qurilish litsenziyasi", "GOST standartlar", "Asfalt zavodi"],
     "contactEmail": "tender@andijan-roads.uz", "contactPhone": "+998 74 225 00 00"},

    {"id": "q-003", "soha": "qurilish", "hudud": "buxoro", "status": "active", "isNew": True,
     "title": "Buxoro shahrini obodonlashtirish — markaziy maydon rekonstruksiyasi",
     "budget": "3 200 000 000", "budgetRaw": 3200000000, "probability": 79, "competitors": 3,
     "deadline": "2026-05-25", "postedDate": "2026-03-01",
     "tags": ["Obodon", "Landshaft", "Meros"], "org": "Buxoro shahar hokimiyati",
     "description": "Labi-Hovuz maydonini rekonstruksiya: yo'lak, chiroqlar, suv fontan, daraxt ekish.",
     "requirements": ["Landshaft dizayn tajribasi", "UNESCO koordinatsiya"],
     "contactEmail": "obod@bukhara.gov.uz", "contactPhone": "+998 65 223 00 00"},

    {"id": "q-004", "soha": "qurilish", "hudud": "samarqand", "status": "active", "isNew": True,
     "title": "Samarqand xalqaro aeroporti kengaytirish loyihasi — 2-terminal",
     "budget": "28 000 000 000", "budgetRaw": 28000000000, "probability": 38, "competitors": 15,
     "deadline": "2026-04-30", "postedDate": "2026-02-20",
     "tags": ["Aeroport", "Terminal", "Infra"], "org": "O'zbekiston Havo Yo'llari",
     "description": "Yangi terminal: 2000 kv.m yo'lovchi zali, 10 ta yo'lakcha, 5 yulduzli VIP lounge.",
     "requirements": ["ICAO standartlar", "Xalqaro qurilish tajriba", "10 mlrd kafolat"],
     "contactEmail": "tender@uzairways.uz", "contactPhone": "+998 71 140 00 00"},

    {"id": "q-005", "soha": "qurilish", "hudud": "namangan", "status": "urgent", "isNew": False,
     "title": "Namangan viloyati qishloq xo'jaligi irrigatsiya tizimi",
     "budget": "5 100 000 000", "budgetRaw": 5100000000, "probability": 71, "competitors": 5,
     "deadline": "2026-04-18", "postedDate": "2026-03-10",
     "tags": ["Irrigatsiya", "Kanal", "Suv"], "org": "Suvxo'jalik Vazirligi",
     "description": "45 km yangi kanal tizimi, 8 ta nasos stantsiyasi, 12,000 gektar yer sug'orish.",
     "requirements": ["Gidroinjenerlik litsenziyasi", "Suvxo'jalik tajribasi"],
     "contactEmail": "tender@suv.gov.uz", "contactPhone": "+998 71 239 00 00"},

    {"id": "q-006", "soha": "qurilish", "hudud": "qashqadaryo", "status": "active", "isNew": False,
     "title": "Qarshi shahri ko'p qavatli uy-joy majmuasi qurilishi",
     "budget": "9 500 000 000", "budgetRaw": 9500000000, "probability": 53, "competitors": 8,
     "deadline": "2026-05-30", "postedDate": "2026-03-05",
     "tags": ["Uy-joy", "Ko'p qavatli", "Prefab"], "org": "Qashqadaryo Qurilish Boshqarmasi",
     "description": "800 xonadon, 5 ta 12 qavatli bino, yer osti avtoturargoh, ko'kalamzor.",
     "requirements": ["Ko'p qavatli qurilish tajribasi", "Bank kafolati 2 mlrd"],
     "contactEmail": "qurilish@qashkadaryo.gov.uz", "contactPhone": "+998 75 221 00 00"},

    # ── TIBBIYOT ─────────────────────────────────────────────────────────
    {"id": "t-001", "soha": "tibbiyot", "hudud": "namangan", "status": "active", "isNew": False,
     "title": "Namangan viloyati shifoxonalari uchun tibbiy jihozlar yetkazib berish",
     "budget": "2 100 000 000", "budgetRaw": 2100000000, "probability": 81, "competitors": 4,
     "deadline": "2026-04-30", "postedDate": "2026-03-01",
     "tags": ["Jihozlar", "MRI", "Laboratoriya"], "org": "Sog'liqni Saqlash Vazirligi",
     "description": "3 ta kasalxona uchun MRI 1.5T, KT skaner, laparoskopik uskunalar, laboratoriya kompleksi.",
     "requirements": ["Tibbiy qurilma sertifikati", "CE/FDA", "Servis kafolati 5 yil"],
     "contactEmail": "jihozlar@ssv.gov.uz", "contactPhone": "+998 71 214 00 00"},

    {"id": "t-002", "soha": "tibbiyot", "hudud": "qashqadaryo", "status": "active", "isNew": False,
     "title": "Qashqadaryo viloyati klinik diagnostika markazini jihozlash",
     "budget": "980 000 000", "budgetRaw": 980000000, "probability": 74, "competitors": 6,
     "deadline": "2026-05-15", "postedDate": "2026-03-08",
     "tags": ["Diagnostika", "PCR", "Ultratovush"], "org": "Qashqadaryo SSB",
     "description": "PCR laboratoriya, 5 ta ultratovush apparati, bioximiya analizatori, hematologiya.",
     "requirements": ["ISO 15189 tajriba", "CE sertifikat", "Reagentlar ta'minoti"],
     "contactEmail": "lab@qashkadaryo-ssb.uz", "contactPhone": "+998 75 221 55 00"},

    {"id": "t-003", "soha": "tibbiyot", "hudud": "toshkent", "status": "urgent", "isNew": True,
     "title": "Respublika shoshilinch tibbiy yordam markazi uchun reanimatsiya jihozlari",
     "budget": "4 500 000 000", "budgetRaw": 4500000000, "probability": 76, "competitors": 5,
     "deadline": "2026-04-22", "postedDate": "2026-03-22",
     "tags": ["Reanimatsiya", "Ventilatsiya", "Monitoring"], "org": "Sog'liqni Saqlash Vazirligi",
     "description": "50 ta ICU karavot, sun'iy nafas oldirish, neinvaziv monitoring, defibrillatorlar.",
     "requirements": ["CE/FDA", "Xalqaro tibbiy kompaniya", "10 yil servis"],
     "contactEmail": "reanm@ssv.gov.uz", "contactPhone": "+998 71 214 11 00"},

    {"id": "t-004", "soha": "tibbiyot", "hudud": "fargona", "status": "active", "isNew": False,
     "title": "Farg'ona shahar onkologiya markazi qurilishi va jihozlanishi",
     "budget": "15 000 000 000", "budgetRaw": 15000000000, "probability": 42, "competitors": 10,
     "deadline": "2026-06-15", "postedDate": "2026-02-28",
     "tags": ["Onkologiya", "Radiologiya", "Kimyoterapiya"], "org": "Sog'liqni Saqlash Vazirligi",
     "description": "100 o'rinlik onkologiya markazi: proton terapiya, PET-CT, operatsiya bloklari.",
     "requirements": ["Tibbiy qurilish tajribasi", "Xalqaro sherikor", "20 mlrd kafolat"],
     "contactEmail": "onko@ssv.gov.uz", "contactPhone": "+998 71 214 22 00"},

    # ── OZIQ-OVQAT ───────────────────────────────────────────────────────
    {"id": "o-001", "soha": "oziq", "hudud": "fargona", "status": "active", "isNew": False,
     "title": "Farg'ona viloyati maktablari uchun ovqatlanish xizmatini ko'rsatish",
     "budget": "890 000 000", "budgetRaw": 890000000, "probability": 88, "competitors": 2,
     "deadline": "2026-04-20", "postedDate": "2026-03-12",
     "tags": ["Maktab", "Ovqat", "HACCP"], "org": "Farg'ona Xalq Ta'limi Boshqarmasi",
     "description": "120 ta maktab, 85,000 o'quvchi uchun kun bo'yi 3 mahal ovqat. 12 oylik shartnoma.",
     "requirements": ["HACCP sertifikati", "3+ yil tajriba", "Sanitariya ruxsati"],
     "contactEmail": "oziq@fergana-edu.uz", "contactPhone": "+998 73 244 00 00"},

    {"id": "o-002", "soha": "oziq", "hudud": "samarqand", "status": "active", "isNew": False,
     "title": "Samarqand viloyati kasalxonalari uchun dieta ovqatlari yetkazish",
     "budget": "650 000 000", "budgetRaw": 650000000, "probability": 91, "competitors": 2,
     "deadline": "2026-05-01", "postedDate": "2026-03-15",
     "tags": ["Dieta", "Kasalxona", "ISO22000"], "org": "Samarqand SSB",
     "description": "8 ta kasalxona, 1200 karavot uchun kuniga 3 mahal dieta ovqat.",
     "requirements": ["ISO 22000", "Tibbiy dieta tajribasi", "Laboratoriya sertifikati"],
     "contactEmail": "ovqat@samarkand-ssb.uz", "contactPhone": "+998 66 235 00 00"},

    {"id": "o-003", "soha": "oziq", "hudud": "toshkent", "status": "active", "isNew": True,
     "title": "Toshkent shahar harbiy qismlar uchun oziq-ovqat ta'minoti",
     "budget": "2 200 000 000", "budgetRaw": 2200000000, "probability": 65, "competitors": 5,
     "deadline": "2026-05-10", "postedDate": "2026-03-20",
     "tags": ["Harbiy", "Konserva", "Logistika"], "org": "Mudofaa Vazirligi",
     "description": "12,000 nafar harbiy xizmatchi uchun yillik oziq-ovqat ta'minoti.",
     "requirements": ["Harbiy ruxsatnoma", "GOST standart", "Maxfiylik shartnoma"],
     "contactEmail": "harbiy-tender@mod.uz", "contactPhone": "+998 71 220 00 00"},

    {"id": "o-004", "soha": "oziq", "hudud": "buxoro", "status": "active", "isNew": False,
     "title": "Buxoro viloyati DYO bolalar muassasalari uchun oziq-ovqat",
     "budget": "380 000 000", "budgetRaw": 380000000, "probability": 85, "competitors": 3,
     "deadline": "2026-04-25", "postedDate": "2026-03-18",
     "tags": ["Bolalar", "Bog'cha", "Organik"], "org": "Buxoro Xalq Ta'limi",
     "description": "35 ta bog'cha, 4500 bola uchun kunlik oziq-ovqat. Organik, sifatli mahsulotlar.",
     "requirements": ["Bolalar oziq-ovqat sertifikati", "HACCP", "Tashish transport"],
     "contactEmail": "ovqat@bukhara-edu.uz", "contactPhone": "+998 65 225 00 00"},

    # ── TRANSPORT ─────────────────────────────────────────────────────────
    {"id": "tr-001", "soha": "transport", "hudud": "qashqadaryo", "status": "active", "isNew": False,
     "title": "Qashqadaryo viloyati shaharlararo avtobus xizmati konsessiyasi",
     "budget": "3 400 000 000", "budgetRaw": 3400000000, "probability": 55, "competitors": 8,
     "deadline": "2026-05-12", "postedDate": "2026-03-01",
     "tags": ["Avtobus", "Marshrut", "GPS"], "org": "Qashqadaryo Hudud Transport",
     "description": "15 ta marshrut, 80 ta yangi avtobus, real-time GPS monitoring, plastik karta to'lov.",
     "requirements": ["Transport litsenziyasi", "GPS tizim", "5+ yil tajriba"],
     "contactEmail": "transport@qashkadaryo.gov.uz", "contactPhone": "+998 75 222 00 00"},

    {"id": "tr-002", "soha": "transport", "hudud": "toshkent", "status": "active", "isNew": True,
     "title": "Toshkent shahri elektr avtobuslar parki shakllantirish",
     "budget": "18 500 000 000", "budgetRaw": 18500000000, "probability": 47, "competitors": 11,
     "deadline": "2026-06-01", "postedDate": "2026-03-25",
     "tags": ["Elektr", "EV Bus", "Charging"], "org": "Toshkent Shahar Transport",
     "description": "200 ta elektr avtobus, 20 ta zaryadlash stantsiyasi, 5 ta depo modernizatsiyasi.",
     "requirements": ["EV tajriba", "Xitoy/Korea zavod", "Servis markazi"],
     "contactEmail": "ev@tashkent-transport.uz", "contactPhone": "+998 71 244 55 00"},

    {"id": "tr-003", "soha": "transport", "hudud": "samarqand", "status": "urgent", "isNew": False,
     "title": "Samarqand xalqaro aeroportiga tez yo'l qurilishi",
     "budget": "22 000 000 000", "budgetRaw": 22000000000, "probability": 41, "competitors": 13,
     "deadline": "2026-04-28", "postedDate": "2026-02-10",
     "tags": ["Yo'l", "Aeroport", "4-yo'l"], "org": "Yo'l Qurilish Vazirligi",
     "description": "12 km 4 yo'lakli magistral yo'l, 2 ta ko'prik, 3 ta yo'l almashinuvi.",
     "requirements": ["Magistral yo'l tajribasi", "250+ xodim", "Uyma-uyma texnika"],
     "contactEmail": "aeroport-road@yolqurilish.uz", "contactPhone": "+998 71 238 00 00"},

    # ── TA'LIM ────────────────────────────────────────────────────────────
    {"id": "ta-001", "soha": "talim", "hudud": "buxoro", "status": "active", "isNew": False,
     "title": "Buxoro viloyati maktablari uchun ta'lim texnologiyalari va interaktiv doskalar",
     "budget": "890 000 000", "budgetRaw": 890000000, "probability": 82, "competitors": 3,
     "deadline": "2026-04-22", "postedDate": "2026-03-10",
     "tags": ["EdTech", "Doska", "Tablet"], "org": "Buxoro Xalq Ta'limi",
     "description": "150 ta maktabga interaktiv doskalar, 3000 ta o'quvchi plansheti, LMS platform.",
     "requirements": ["EdTech tajribasi", "Mahalliy texnik qo'llab-quvvatlash", "Warranty 3 yil"],
     "contactEmail": "edtech@bukhara-edu.uz", "contactPhone": "+998 65 224 00 00"},

    {"id": "ta-002", "soha": "talim", "hudud": "toshkent", "status": "active", "isNew": False,
     "title": "Toshkent shahri maktab kutubxonalari uchun elektron kitoblar platformasi",
     "budget": "540 000 000", "budgetRaw": 540000000, "probability": 76, "competitors": 5,
     "deadline": "2026-06-01", "postedDate": "2026-03-15",
     "tags": ["E-kitob", "Platform", "API"], "org": "Toshkent Xalq Ta'limi",
     "description": "200,000+ elektron kitob, 300 ta maktab, offline rejim.",
     "requirements": ["Digital publishing tajriba", "Mobile app (iOS/Android)", "Mualliflik huquqlari"],
     "contactEmail": "ekitob@tashkent-edu.uz", "contactPhone": "+998 71 239 55 00"},

    {"id": "ta-003", "soha": "talim", "hudud": "andijon", "status": "active", "isNew": False,
     "title": "Andijon viloyati kasb-hunar maktablari uchun asbob-uskunalar",
     "budget": "1 200 000 000", "budgetRaw": 1200000000, "probability": 69, "competitors": 6,
     "deadline": "2026-05-18", "postedDate": "2026-03-08",
     "tags": ["KHM", "Stanok", "Asbob"], "org": "Andijon Kasb-Hunar Ta'lim",
     "description": "25 ta KHM uchun CNC dastgohlar, elektr uskunalar, Arduino laboratoriyalar.",
     "requirements": ["Ta'lim uskunalari litsenziyasi", "Texnik training", "Zapchastlar ta'minot"],
     "contactEmail": "khm@andijan-edu.uz", "contactPhone": "+998 74 226 00 00"},

    {"id": "ta-004", "soha": "talim", "hudud": "namangan", "status": "active", "isNew": True,
     "title": "Namangan IT Park — dasturlash o'quv markazi jihozlash",
     "budget": "750 000 000", "budgetRaw": 750000000, "probability": 84, "competitors": 3,
     "deadline": "2026-05-05", "postedDate": "2026-03-22",
     "tags": ["IT Park", "Server", "Mac"], "org": "IT Park O'zbekiston",
     "description": "300 xonali o'quv sinf: Mac/Windows kompyuterlar, server lab, AI/ML workstation.",
     "requirements": ["Apple reseller yoki HP/Dell", "Tarmoq muhendisi", "3 yil kafolat"],
     "contactEmail": "tender@itpark.uz", "contactPhone": "+998 71 202 00 00"},

    {"id": "ta-005", "soha": "talim", "hudud": "fargona", "status": "active", "isNew": False,
     "title": "Farg'ona viloyati ingliz tili markazlari uchun audio-video qo'llanmalar",
     "budget": "320 000 000", "budgetRaw": 320000000, "probability": 77, "competitors": 4,
     "deadline": "2026-05-20", "postedDate": "2026-03-12",
     "tags": ["Ingliz tili", "IELTS", "Multimedia"], "org": "Farg'ona Xalq Ta'limi",
     "description": "50 ta ingliz tili markazi uchun: Smart TV, audio sistema, IELTS materiallari.",
     "requirements": ["Multimedia jihozlar", "Ta'lim kontenti", "Kafedra tavsiyasi"],
     "contactEmail": "ingliz@fergana-edu.uz", "contactPhone": "+998 73 245 00 00"},

    # ── EKOLOGIYA ────────────────────────────────────────────────────────
    {"id": "ek-001", "soha": "ekologiya", "hudud": "toshkent", "status": "active", "isNew": True,
     "title": "Toshkent shahar chiqindilarni qayta ishlash zavodi",
     "budget": "35 000 000 000", "budgetRaw": 35000000000, "probability": 32, "competitors": 18,
     "deadline": "2026-06-01", "postedDate": "2026-03-01",
     "tags": ["Recycling", "Zavodla", "Ekologiya"], "org": "Ekologiya Vazirligi",
     "description": "Kuniga 1500 tonna chiqindi qayta ishlash zavodi.",
     "requirements": ["Zavodchilik tajribasi", "EU standartlar", "50 mlrd kafolat"],
     "contactEmail": "tender@ekologiya.gov.uz", "contactPhone": "+998 71 200 88 00"},

    {"id": "ek-002", "soha": "ekologiya", "hudud": "buxoro", "status": "active", "isNew": False,
     "title": "Buxoro viloyati quyosh energiyasi stantsiyasi (50 MVt)",
     "budget": "42 000 000 000", "budgetRaw": 42000000000, "probability": 28, "competitors": 20,
     "deadline": "2026-05-25", "postedDate": "2026-02-15",
     "tags": ["Quyosh", "Solar", "Energiya"], "org": "Energetika Vazirligi",
     "description": "50 MVt quvvatli quyosh elektr stantsiyasi, transformator, 110 kV tarmoq ulash.",
     "requirements": ["Xalqaro solar tajriba", "IFC/EBRD moliyasi", "EPC shartnoma"],
     "contactEmail": "solar@energetika.gov.uz", "contactPhone": "+998 71 238 55 00"},

    # ── QISHLOQ XO'JALIGI ────────────────────────────────────────────────
    {"id": "qx-001", "soha": "qishloq", "hudud": "xorazm", "status": "active", "isNew": True,
     "title": "Xorazm viloyati dehqonchilik uchun smart agro texnologiyalari",
     "budget": "1 600 000 000", "budgetRaw": 1600000000, "probability": 73, "competitors": 4,
     "deadline": "2026-05-15", "postedDate": "2026-03-20",
     "tags": ["Smart Agro", "Drone", "IoT"], "org": "Qishloq Xo'jalik Vazirligi",
     "description": "Dron purkash tizimi, IoT namlik sensori, avtomatik sug'orish, agro monitoring platform.",
     "requirements": ["Agro-tech tajribasi", "Drone litsenziyasi", "IoT platforma"],
     "contactEmail": "agro@qxv.gov.uz", "contactPhone": "+998 71 239 77 00"},

    {"id": "qx-002", "soha": "qishloq", "hudud": "surxondaryo", "status": "active", "isNew": False,
     "title": "Surxondaryo viloyati issiqxona kompleksi qurilishi",
     "budget": "2 800 000 000", "budgetRaw": 2800000000, "probability": 61, "competitors": 7,
     "deadline": "2026-05-30", "postedDate": "2026-03-05",
     "tags": ["Issiqxona", "Gidroponik", "Export"], "org": "Qishloq Xo'jalik Vazirligi",
     "description": "20 gektar zamonaviy Venlo-tip issiqxona, gidroponik tizim, sovutgich omborlar.",
     "requirements": ["Issiqxona qurilish tajribasi", "Export sertifikati", "Netherlands standart"],
     "contactEmail": "issiqxona@qxv.gov.uz", "contactPhone": "+998 71 239 88 00"},
]
